### ISSUE TITLE
No machine id

### ISSUE THREAD

**Issue by loganfreeman** [agiledivider/vagrant-hostsupdater#102]
==> node-3: [vagrant-hostsupdater] No machine id, nothing removed from C:/WINDOWS/system32/drivers/etc/hosts
==> node-3: VM not created. Moving on...
==> node-3: [vagrant-hostsupdater] Checking for host entries
C:/HashiCorp/Vagrant/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb:126:in `digest': no implicit conversion of nil into String (TypeError)
        from C:/HashiCorp/Vagrant/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/HostsUpdater.rb:126:in`hexdigest'

**Comment by cgsmith** [comment]
Thanks for the report @loganfreeman I'll get this fixed in the next release.

**Comment by emgk** [comment]
Is it fixed ? or any alternative way to get rid out of it ? @cgsmith

**Comment by cgsmith** [comment]
hi @emgk - i do not have a fix for this yet. PRs welcome.

**Comment by geerlingguy** [comment]
I'm getting this today after updating to the latest version of Vagrant...

```
$ vagrant up             
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
Traceback (most recent call last):
	32: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
	31: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
	30: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
...
	10: from /opt/vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
	 9: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:17:in `call'
	 8: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:35:in `addHostEntries'
	 7: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:35:in `each'
	 6: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:36:in `block in addHostEntries'
	 5: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:36:in `each'
	 4: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:42:in `block (2 levels) in addHostEntries'
	 3: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:73:in `createHostEntry'
	 2: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:126:in `signature'
	 1: from /Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:126:in `hexdigest'
/Users/jgeerling/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:126:in `digest': no implicit conversion of nil into String (TypeError)
```

**Comment by cgsmith** [comment]
@geerlingguy can you test this out? https://github.com/agiledivider/vagrant-hostsupdater/releases/tag/1.2.0-beta

**Comment by geerlingguy** [comment]
@cgsmith - That download worked perfect, thanks!

**Comment by peteeckel** [comment]
Though I'm not @geerlingguy, I've just tested it and it works - although it seems pretty noisy to me:

```
pete@macallan imcs % vagrant up master2                                                                    
Bringing machine 'master2' up with 'virtualbox' provider...
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> master2: [vagrant-hostsupdater]   192.168.110.112  master2.example.com  # VAGRANT: 6a4caf85cf0a010b4d9dba92666579ef (master2) / c9721e83-165a-4dab-814d-a984b4f356eb
==> master2: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: Clearing any previously set forwarded ports...
==> master2: Fixed port collision for 22 => 2222. Now on port 2200.
==> master2: Clearing any previously set network interfaces...
==> master2: Preparing network interfaces based on configuration...
    master2: Adapter 1: nat
    master2: Adapter 2: hostonly
==> master2: Forwarding ports...
    master2: 22 (guest) => 2200 (host) (adapter 1)
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: Running 'pre-boot' VM customizations...
==> master2: Booting VM...
==> master2: Waiting for machine to boot. This may take a few minutes...
    master2: SSH address: 127.0.0.1:2200
    master2: SSH username: vagrant
    master2: SSH auth method: private key
==> master2: Machine booted and ready!
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: Checking for guest additions in VM...
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: Setting hostname...
==> master2: Configuring and enabling network interfaces...
==> master2: Mounting shared folders...
    master2: /vagrant => /Users/pete/Documents/Vagrant/imcs
==> master2: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> master2: flag to force provisioning. Provisioners marked to run always will still run.
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
==> master2: [vagrant-hostsupdater] Checking for host entries
==> master2: [vagrant-hostsupdater]   found entry for: 192.168.110.112 master2.example.com
```

**Comment by geerlingguy** [comment]
@peteeckel - Heh, I noticed that too. 12 times when you do a reload! I think the main problem is Vagrant changed how it calls out to plugins in the latest version somehow—I noticed the `vagrant-vbguest` plugin is also dumping duplicate output a lot:

```
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.1.12
VBoxService inside the vm claims: 6.1.16
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.1.12
VBoxService inside the vm claims: 6.1.16
Going on, assuming VBoxService is correct...
Got different reports about installed GuestAdditions version:
Virtualbox on your host claims:   6.1.12
VBoxService inside the vm claims: 6.1.16
Going on, assuming VBoxService is correct...
Restarting VM to apply changes...
```

**Comment by peteeckel** [comment]
`vagrant halt` isn't much better either:

```
==> master1: Attempting graceful shutdown of VM...
==> master1: [vagrant-hostsupdater] Removing hosts
==> master1: [vagrant-hostsupdater] Removing hosts
==> master1: [vagrant-hostsupdater] Removing hosts
==> master1: [vagrant-hostsupdater] Removing hosts
==> master1: [vagrant-hostsupdater] Removing hosts
==> master1: [vagrant-hostsupdater] Removing hosts
==> master1: [vagrant-hostsupdater] Removing hosts
==> master1: [vagrant-hostsupdater] Removing hosts
```

But on the other hand it's working again.

**Comment by geerlingguy** [comment]
@peteeckel - Heh, it's just being _really, really thorough_.
